/*
AUTHOR: IAGO GOUVEIA GURGEL
THIS IS A SOURCE FILE FOR A CODING PROJECT, EVERY LINE OF CODE PRODUCED
SHALL FOLLOW GNU CODING STANDARDS DEFINED IN
https://www.gnu.org/prep/standards/standards.html
*/
